<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\Abilities\MonsterAbilities\**" />
    <Compile Remove="Models\Characters\Npcs\**" />
    <Compile Remove="Models\Rooms\**" />
    <EmbeddedResource Remove="Models\Abilities\MonsterAbilities\**" />
    <EmbeddedResource Remove="Models\Characters\Npcs\**" />
    <EmbeddedResource Remove="Models\Rooms\**" />
    <None Remove="Models\Abilities\MonsterAbilities\**" />
    <None Remove="Models\Characters\Npcs\**" />
    <None Remove="Models\Rooms\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Migrations\Scripts\InitialSeedData.rollback.sql" />
    <None Remove="Migrations\Scripts\InitialSeedData.sql" />
    <None Remove="Migrations\Scripts\SeedEquipment.rollback.sql" />
    <None Remove="Migrations\Scripts\SeedEquipment.rollback.sql~RF8555f2c5.TMP" />
    <None Remove="Migrations\Scripts\SeedEquipment.sql" />
    <None Remove="Models\Abilities\Ability.cs~RF7a28a58b.TMP" />
    <None Remove="Models\Attributes\ITargetable.cs~RF7fb34c69.TMP" />
    <None Remove="Models\Equipments\Inventory.cs~RFae3eb4d5.TMP" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Migrations\Scripts\SeedEquipment.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Migrations\Scripts\SeedEquipment.rollback.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Migrations\Scripts\InitialSeedData.rollback.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Migrations\Scripts\InitialSeedData.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.35" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.35">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="6.0.35" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.35" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.35">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="6.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
    <PackageReference Include="NReco.Logging.File" Version="1.2.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Migrations\Scripts\SeedItems.rollback.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Migrations\Scripts\SeedItems.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
